### ISSUE TITLE
Error connection mongoldb to viscose ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by fadelfffar** [mongodb-js/vscode#411]
Hi all,

OS: MacOS Monterey (12.3.1)
VSCode: 1.66.2
MongoDB Extension: 0.9.2

I just had some issue connecting to a MongoDB server running inside Visual Code

I kept getting the following error: Unable to connect: getaddrinfo ECONNREFUSED 127.0.0.1:27017 mongoldb and i can't seem to figure out the solution for it
![Screen Shot 2022-04-30 at 10 32 05](https://user-images.githubusercontent.com/58397488/166088966-084b8dd3-2195-404a-a25b-1d182856189a.png)

**Comment by Anemy** [comment]
Hi @fadelfffar - could you tell us a little more about your MongoDB instance you are trying to connect to? Is it running on your machine on the port 27017? Is it bound to `localhost` or `127.0.0.1`?

Are you able to connect to the same instance using the [MongoDB Shell](https://www.mongodb.com/try/download/shell) `mongosh`?

**Comment by sadokmtir** [comment]
@Anemy I am also having the sam problem. I could connect with robo 3T. I have a Mongo server running in a docker compose:
```
  mongo:
    image: mongo:4.2.19-bionic
    command: ["--replSet", "rs0"]
    restart: unless-stopped
    volumes:
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
    ports:
      - 27017:27017

```
